### PR TITLE
test against 3.7 and 3.8, drop 2.7

### PR DESCRIPTION
**Pull request by jhamman**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Can you also add a `python_requires='>=3.6'` (or 3.5?) in the setup.py?

**Comment by TomAugspurger** [comment]
And I suppose classifiers for 3.6 - 3.8

```
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
    ],
```

**Comment by jhamman** [comment]
Thanks @TomAugspurger and @jrbourbeau - last question, who can make a release?

**Comment by jrbourbeau** [comment]
@TomAugspurger is currently a maintainer on PyPI. Tom, feel free to add me and I can push out a release

**Comment by TomAugspurger** [comment]
I can push to PyPI. I'll start on that in a bit.

**Comment by TomAugspurger** [comment]
Added you as a collaborator James, but I handled the release.

Actually, two releases, since PyPI rejected my first upload with a bad
content type for the description. That was fixed in
https://github.com/dask/cachey/commit/c8aec8f354cc1166e2f9e6d8e1fc9be454708c36
(apologies for pushing to master) and 0.2.1 was pushed right after.

**Comment by jhamman** [comment]
huzzah! Thanks folks!

**Comment by jrbourbeau** [comment]
Woo, thanks @TomAugspurger!

**Pull request merged**
